### ISSUE TITLE
App crashes when typing something into the UISearchBar sample

### ISSUE THREAD

**Issue by 343max** [mattgallagher/CwlViews#1]
Simply removing `searchText` from the `multiHandler` call in `searchBar(_, textDidChange)` seems to resolve this issue, but this code is wayyyyyy over my head to even understand if this is a acceptable solution. (Although it seems to work)

**Comment by mattgallagher** [comment]
Hi @343max, thanks for letting me know.

The Binding was defined as `(UISearchBar) -> Void` but the underlying delegate method is `(UISearchBar, String) -> Void` so the force-cast that `multiHandler` does internally (to recover the handler function) was failing.

I've fixed the definition and the crash in f4438772381b054fa68a6cb04b0d226c023297f8
